### PR TITLE
Features for main.py --path <directory or images.txt> --box2seg --yolo_subdir

### PR DESCRIPTION
**Pull request by NauchtanRobotics**
Hi, 

I understand there is way too much in here for one branch, plus I used the 'black' formatting lib so not many lines haven't been changed.

Please let me know if you would like individual pull request provided for any of the following features in this PR:
* main.py --path | Changed code so that you can pass a directory instead OR a text file.  That way you only have to run one command instead of running path_replacer.py in advance of main.py
* main.py --box2seg | I made this so I can port my yolo bounding boxes over to segmentation for use in Mask-RCNN modelling. This will save a lot of time preparing polygons, particularly when a box shaped polygon is acceptable.
* main.py --yolo-subdir | I made this because I've been using OpenLabeling which puts image annotations in a sub-directory call 'YOLO_darknet'.

I'd be happy to create unit tests to support any of these features.

### CODE REVIEW

**Comment by Taeyoung96** [comment]
@NauchtanRobotics   
Thanks for your PR!  

As I understand,  
When I merge this patch, I can make COCO format annotation with OpenLabeling and  
Yolo bounding box to segmentation annotation.  

I think your idea is great.  
BTW `.idea/.gitignore` is not necessary on this repository and It would be nice if there was a description of the added functions in `Readme.md`.  

Thanks,

**Comment by NauchtanRobotics** [comment]
Hi, 

Yes it sounds like you understand correctly.

I will update the README.md. Besides updating the README, I need to fix a technical issue. The segmentation field in the output require the coordinates to be inside a nested list, e.g. 
`[ [x1, y1, x2, y2,... xn, yn] ]`

So hold off on merge for the moment.

David

**Comment by Taeyoung96** [comment]
@NauchtanRobotics  

Great.  
When you fixed some issues and update README.md, just mention me one more time!  

You could make another PR or just commit with the updated code.  

Thanks,

**Comment by NauchtanRobotics** [comment]
@Taeyoung96 I've updated the README. How does this look?

**Comment by NauchtanRobotics** [comment]
BTW I can drop the commit that formats/indents the coco json file if output minimisation is critical.
I also noted that makesense.ai indexes the image_id from 1 (like class_id) but annotation_id from 0. Did you want those changes too?

**Comment by NauchtanRobotics** [comment]
@Taeyoung96 README updated. How does this look?

**Review by Taeyoung96 — APPROVED** [review]
It looks great. Thanks for your contribution!  :smile:

**Pull request merged**
